/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/_layout'
import { Route as AuthenticatedAppLayoutRouteImport } from './routes/_authenticated/_app/_layout'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicRequestAccessRouteImport } from './routes/_public/request-access'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as AuthenticatedAppHouseholdRouteImport } from './routes/_authenticated/_app/household'
import { Route as PublicInviteTokenRouteImport } from './routes/_public/invite.$token'
import { Route as AuthenticatedAppRecipesIndexRouteImport } from './routes/_authenticated/_app/recipes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppLayoutRoute = AuthenticatedAppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicRequestAccessRoute = PublicRequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthenticatedAppHouseholdRoute =
  AuthenticatedAppHouseholdRouteImport.update({
    id: '/household',
    path: '/household',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any)
const PublicInviteTokenRoute = PublicInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthenticatedAppRecipesIndexRoute =
  AuthenticatedAppRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/request-access': typeof PublicRequestAccessRoute
  '/terms': typeof PublicTermsRoute
  '/household': typeof AuthenticatedAppHouseholdRoute
  '/invite/$token': typeof PublicInviteTokenRoute
  '/recipes/': typeof AuthenticatedAppRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/request-access': typeof PublicRequestAccessRoute
  '/terms': typeof PublicTermsRoute
  '/household': typeof AuthenticatedAppHouseholdRoute
  '/invite/$token': typeof PublicInviteTokenRoute
  '/recipes': typeof AuthenticatedAppRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppLayoutRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/request-access': typeof PublicRequestAccessRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_authenticated/_app/household': typeof AuthenticatedAppHouseholdRoute
  '/_public/invite/$token': typeof PublicInviteTokenRoute
  '/_authenticated/_app/recipes/': typeof AuthenticatedAppRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/privacy'
    | '/request-access'
    | '/terms'
    | '/household'
    | '/invite/$token'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/privacy'
    | '/request-access'
    | '/terms'
    | '/household'
    | '/invite/$token'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_public/privacy'
    | '/_public/request-access'
    | '/_public/terms'
    | '/_authenticated/_app/household'
    | '/_public/invite/$token'
    | '/_authenticated/_app/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/request-access': {
      id: '/_public/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof PublicRequestAccessRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_authenticated/_app/household': {
      id: '/_authenticated/_app/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthenticatedAppHouseholdRouteImport
      parentRoute: typeof AuthenticatedAppLayoutRoute
    }
    '/_public/invite/$token': {
      id: '/_public/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof PublicInviteTokenRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_authenticated/_app/recipes/': {
      id: '/_authenticated/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedAppRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedAppLayoutRoute
    }
  }
}

interface AuthenticatedAppLayoutRouteChildren {
  AuthenticatedAppHouseholdRoute: typeof AuthenticatedAppHouseholdRoute
  AuthenticatedAppRecipesIndexRoute: typeof AuthenticatedAppRecipesIndexRoute
}

const AuthenticatedAppLayoutRouteChildren: AuthenticatedAppLayoutRouteChildren =
  {
    AuthenticatedAppHouseholdRoute: AuthenticatedAppHouseholdRoute,
    AuthenticatedAppRecipesIndexRoute: AuthenticatedAppRecipesIndexRoute,
  }

const AuthenticatedAppLayoutRouteWithChildren =
  AuthenticatedAppLayoutRoute._addFileChildren(
    AuthenticatedAppLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedAppLayoutRoute: typeof AuthenticatedAppLayoutRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedAppLayoutRoute: AuthenticatedAppLayoutRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface PublicLayoutRouteChildren {
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRequestAccessRoute: typeof PublicRequestAccessRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicInviteTokenRoute: typeof PublicInviteTokenRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRequestAccessRoute: PublicRequestAccessRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicInviteTokenRoute: PublicInviteTokenRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
